// <auto-generated />
namespace QuizYourLizardApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _20140423 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20140423));
        
        string IMigrationMetadata.Id
        {
            get { return "201404231834599_20140423"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
